### ISSUE TITLE
ModuleNotFoundError: No module named 'gp_extras.tomographer.tomography.custom_tv'

### ISSUE THREAD

**Issue by xjs1996** [lamanno-epfl/tomographer#1]
Hi,guys:
    I've read your paper, very excellent work!
    I'm trying to run tutorial1, but it seems like that you've missed custome_tv in tomography, thus, optimization.py in tomograpy can not import tv_masked and make_tv_ixmask. Would you mind release some data for test? Beacause it is hard to understand what the data looks like when I read "var: dictionary containing gene_list and attributes" .It will be nice if you can also offer some test data for "tomography/tomorun.py".
    best wishes.

xjs

**Comment by hhschede** [comment]
Hello. Thank you very much for bringing this our attention. Import of the .optimization module should no longer throw the issue. Could you please verify?

We will add some test data for tutorial2 soon. 

Warm regards,

Hannah

**Comment by xjs1996** [comment]
Hi, I've downloaded your new version of tomographer and when I tested tutorial1, I found a new error in core.py in tomography: ImportError: cannot import name 'toimage' from 'scipy.misc'. I searched it on the internet, and someone says 'toimage' has been canceled from scipy. Are you still using this package? If so, could you please tell me the version of 'scipy'?

**Comment by hhschede** [comment]
I have updated the README with the specific versions for the packages.

`conda create -n tomographer-env python=3.7 numpy=1.19.0 scipy=1.2.0 pandas=0.24.1 scikit-learn=0.20.2 scikit-image=0.14.2 matplotlib=3.0.2 --channel bioconda --channel conda-forge`

**Comment by xjs1996** [comment]
Hi, Hannah. I see you have add "/data/TOMOGRAPHY/data/Lizard%s_layout.txt" &  "/data/TOMOGRAPHY/data/Lizard%s_expression.cef" in tutorial2, but both of them are not exist in your package, please update when you are convenient. Thank you so much~
Best regards.

**Comment by hhschede** [comment]
Hello,

Unfortunately we will not be releasing this data until the work is
published. Hopefully this will be in the coming weeks.

Warm regards,

H Schede

**Comment by chrstnschndr** [comment]
Hello @xjs1996, 

we have just updated Tutorial 2 with a description where the data you are asking for can be found. 
- the **expression** data was released along with our preprint and is available via Gene Expression Omnibus repository (GEO; https://www.ncbi.nlm.nih.gov/geo) under accession GSE152989. 

- for the **layout.txt** files, please refer to https://github.com/lamanno-epfl/tomographer/tree/master/supplementary_resources/layout_files

With these files you should have everything at hand for a successful completion of our tutorials. Thanks for your interest and for bringing to our attention that these files were not trivial to find. Feel free to reach out if you have any further questions.

Best,

Christian

**Comment by xjs1996** [comment]
Hi, Christian, Thank you so much for your kindness~ I have one more question: How to convert the *.tab file to *.cef file? I've read information about ceftools(https://github.com/linnarsson-lab/ceftools), but didn't figure out how to change the file format. Looking forward to your reply.

Best regards,
xjs

**Comment by chrstnschndr** [comment]
Hello @xjs1996, 

thanks for your interest. Please have a look into the ceftools readme, I believe it does an excellent job of providing you with documentation needed to do the job (https://github.com/linnarsson-lab/ceftools/blob/master/README.md). 

For convenience, we will also provide the final .cef files. In order to do so, we have sent the .cef files to our GEO (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE152989). Note, that they have not been uploaded yet (as it takes a while for them to update the repository) but I am expecting them to appear soon in the list of Supplementary Files.

Good luck and fun exploring our method!

Best,

Christian




---*edit: now .cef files are available as GSE152989_new_suppl_files.tar.gz---

**Comment by xjs1996** [comment]
Got it, Thank you so much~

**Comment by xjs1996** [comment]
Hi, Christian, the pickle files and hdf5 files are also missed. Would you like releasing them?

**Comment by chrstnschndr** [comment]
Dear @xjs1996 ,

- The ref images (as pickle files) can be found in the repository ../supplementary_resources/ref_imgs
- The hdf5 files are created by yourself and the algorithm. Please refer to http://tomographer.info/summary.html for a detailed perspective on them. In brief: The configuration.hdf5 and the inputProjection.hdf5 are created by you in the notebook (see Tutorial2 "Writing Data to the Specified Format". They are subsequently used as an input to the reconstruction command (together with a list.txt of genes to be reconstructed) (see Perform Reconstruction in the notebook or use the command line input to tomorun.py). The reconstruction algorithm outputs a reconstruction.hdf5 and an AlphaBeta.hdf5 which can be used to plot reconstructions and to perform analysis.

Best, 

Christian

**Comment by xjs1996** [comment]
Sorry I didn't see them, and thanks for your reply and patience.
