### ISSUE TITLE
About "brainmap"

### ISSUE THREAD

**Issue by xjs1996** [lamanno-epfl/tomographer#2]
Hi, I'm runnning tutorial1, and sorry that I faced a problem again, your code are as following:

# Tomography
import tomography
from tomography.utils import pad_to_cube, pad_to_square, shift_simmetrize
from brainmap import *

but I cannot install package "brainmap". Can you tell me which package is it? Thank you so much~

**Comment by hhschede** [comment]
Hello, we have added brainmap to the dependencies in the ReadMe.
please see: https://github.com/linnarsson-lab/brainmap

**Comment by xjs1996** [comment]
Thank you, Hannah! I installed this package successfully.(ha ha)
